[ABOUT]
NAME = Crystal Gauges Rewrite
AUTHOR = After
VERSION = 1.6.0
DESCRIPTION = Rewritten version of my Crystal Gauges
REQUIRED_VERSION = 0
URL = https://github.com/Afterro/Crystal-Gauges-v2/

[CORE]
LAZY = PARTIAL
; • NONE (or 0, default value): load script when Assetto Corsa is loading, run it until it’s closed
; • PARTIAL (or 1): load script only when app is first opened, after that keep it running until Assetto Corsa is closed.
; • FULL (or 2): load script when app is opened, when all windows are closed, unload an app completely.
; Note: when app unloads, all of its internal state (apart from stored with things like `ac.connect()`, 
; `ac.storage()` or `ac.store()`) is completely lost. That’s why sometimes it might make more sense to
; use partial laziness and unload app manually on closing (for example, if your app has manual saving
; and a user closed or hid window without saving).
  ; • AUTO_RESIZE: automatically resizes window to fit its content
  ; • DARK_HEADER: black font and symbols in titlebar
  ; • FADING: makes window fade when inactive, similar to chat app
  ; • FIXED_SIZE: prevents window from being resized
  ; • FLOATING_TITLE_BAR: text and symbols floating/stacked
  ; • HIDDEN_OFFLINE: makes the window hidden when in a singleplayer (offline) session (useful if the app use is not intended for offline)
  ; • HIDDEN_ONLINE: makes the window hidden when connected to an online server (useful if the app uses functions not available online)
  ; • HIDDEN_RENDER_CUSTOM: hide in custom screen setup
  ; • HIDDEN_RENDER_SINGLE: hide in single screen mode
  ; • HIDDEN_RENDER_TRIPLE: hide in triple screen
  ; • HIDDEN_RENDER_VR: hide in VR
  ; • MAIN: makes window act like main window (if not set, first window gets that role)
  ; • NO_BACKGROUND: makes background transparent
  ; • NO_COLLAPSE: hides collapse button
  ; • NO_SCROLL_WITH_MOUSE: stops mouse wheel from scrolling
  ; • NO_SCROLLBAR: hides scrollbar 
  ; • NO_TITLE_BAR: hides title bar
  ; • SETTINGS: adds settings button next to collapse and close buttons in title bar, opening settings window
  ; • SETUP: show in setup screen 
  ; • SETUP_HIDDEN: show on setup menu but not in app list

; [WINDOW_...]
; ID = "settings"
; NAME = "Crystal Gauges V2"
; ICON = icons/settings.png
; FUNCTION_MAIN = windowSettings
; ; FUNCTION_SETTINGS = windowSettings ; optional
; SIZE = 500,500
; PADDING = 10,10
; FLAGS = MAIN

[WINDOW_...]
ID = "tacho"
NAME = "Tacho"
ICON = icons/tacho.png
FUNCTION_MAIN = windowTacho
FUNCTION_SETTINGS = tachoSettings ; optional
PADDING = 0,0
SIZE = 280,280
FLAGS = SETTINGS, NO_BACKGROUND, NO_SCROLLBAR, NO_SCROLL_WITH_MOUSE, FADING, AUTO_RESIZE, FLOATING_TITLE_BAR

[WINDOW_...]
ID = "minimap"
NAME = "Minimap"
ICON = icons/map.png
FUNCTION_MAIN = windowMinimap
FUNCTION_SETTINGS = tachoSettings ; optional
PADDING = 0,0
SIZE = 192,192
FLAGS = NO_SCROLLBAR, NO_SCROLL_WITH_MOUSE, NO_COLLAPSE, FLOATING_TITLE_BAR,FIXED_SIZE, NO_BACKGROUND

[WINDOW_...]
ID = "media"
NAME = "Media"
ICON = icons/media.png
FUNCTION_MAIN = windowMedia
FUNCTION_SETTINGS = tachoSettings ; optional
PADDING = 0,0
SIZE = 192,32
FLAGS = NO_SCROLLBAR, NO_SCROLL_WITH_MOUSE, NO_COLLAPSE, FLOATING_TITLE_BAR,FIXED_SIZE, NO_BACKGROUND

[WINDOW_...]
ID = "inputs"
NAME = "Inputs"
ICON = icons/inputs.png
FUNCTION_MAIN = windowInputs
FUNCTION_SETTINGS = tachoSettings ; optional
PADDING = 0,0
SIZE = 250,50
FLAGS = NO_SCROLLBAR, NO_SCROLL_WITH_MOUSE, NO_COLLAPSE, FLOATING_TITLE_BAR,FIXED_SIZE, NO_BACKGROUND

; optional
[RENDER_CALLBACKS]
TRANSPARENT = Draw3D